# Generated by Django 4.0.4 on 2022-05-23 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'De-active')], default='1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=None, max_length=500)),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'De-active')], default='1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(default='0', null=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=None, max_length=500)),
                ('title', models.CharField(default=None, max_length=500)),
                ('desc_short', models.TextField()),
                ('desc_long', models.TextField()),
                ('specification', models.TextField()),
                ('dashed_price', models.FloatField(blank=True, default=None, null=True)),
                ('actual_price', models.FloatField(blank=True, default=None, null=True)),
                ('stock_count', models.IntegerField(default=0)),
                ('is_published', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=20)),
                ('is_in_sale', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coreapp.brand')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coreapp.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=250)),
                ('path', models.ImageField(default='product/no-data.png', upload_to='product/images')),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'De-active')], default='1', max_length=20)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coreapp.product')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
