# Generated by Django 4.0.4 on 2022-05-27 05:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to='coreapp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc_long',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
