# Generated by Django 4.0.4 on 2022-05-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_product_actual_price_product_dashed_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='path',
            field=models.ImageField(default='static/product/no-data.png', upload_to='static/product/images'),
        ),
    ]
