# Generated by Django 4.0.4 on 2022-05-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_alter_productimage_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='path',
            field=models.ImageField(default='product/no-data.png', upload_to='product/images'),
        ),
    ]
