# Generated by Django 4.0.4 on 2022-05-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_product_slug_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'De-active')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'De-active')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_in_sale',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'De-active')], default='1', max_length=20),
        ),
    ]
